version: '3.7'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379" 

  rate-limiter:
    build: .
    container_name: rate-limiter-with-go
    ports:
      - 8080:8080
    environment:
      - REDIS_ADDR=redis:6379
      - RATE_LIMIT_IP=1
      - RATE_LIMIT_TOKEN=2
      - BLOCK_DURATION=5 # em segundos


  rate-limiter-tests:
    build: ./tests
    container_name: rate-limiter-tests
    depends_on:
      - rate-limiter
    environment:
      - URL_RATE=rate-limiter
